export const ASSET_CATEGORIES: Record<string, string> = {
  BTC: "Layer 1",
  ETH: "Smart Contracts",
  SOL: "Layer 1",
  XRP: "Finance",
  ADA: "Layer 1",
  DOT: "Layer 1",
  AVAX: "Layer 1",
  ATOM: "Layer 1",
  ALGO: "Layer 1",
  NEAR: "Layer 1",
  SUI: "Layer 1",
  APT: "Layer 1",
  SEI: "Layer 1",
  HBAR: "Layer 1",
  ICP: "Internet",
  FIL: "Storage",
  KAS: "Layer 1",
  TON: "Layer 1",
  XLM: "Finance",
  EOS: "Layer 1",
  EGLD: "Layer 1",
  KSM: "Layer 1",
  MINA: "Layer 1",
  ONE: "Layer 1",
  ROSE: "Layer 1",
  CSPR: "Layer 1",
  FLOW: "Layer 1",
  NEO: "Smart Contracts",
  THETA: "Web3",
  XTZ: "Smart Contracts",
  FTM: "Layer 1",
  CELO: "Layer 1",
  ZIL: "Layer 1",
  CKB: "Layer 1",
  QTUM: "Smart Contracts",
  ICX: "Layer 1",
  WAVES: "Smart Contracts",
  IOTA: "IoT",

  ARB: "Layer 2",
  OP: "Layer 2",
  POL: "Layer 2",
  MATIC: "Layer 2",
  IMX: "Layer 2",
  SKL: "Layer 2",
  STX: "Layer 2",
  VAULTA: "Layer 2",

  UNI: "DeFi",
  AAVE: "DeFi",
  COMP: "DeFi",
  MKR: "DeFi",
  SNX: "DeFi",
  SUSHI: "DeFi",
  CRV: "DeFi",
  YFI: "DeFi",
  LDO: "DeFi",
  "1INCH": "DeFi",
  DYDX: "DeFi",
  JUP: "DeFi",
  RAY: "DeFi",
  ORCA: "DeFi",
  QI: "DeFi",
  KAVA: "DeFi",
  SPELL: "DeFi",
  ANKR: "DeFi",
  VVS: "DeFi",
  TONIC: "DeFi",
  CELR: "DeFi",
  OOKI: "DeFi",
  UMA: "DeFi",
  REEF: "DeFi",
  BLZ: "DeFi",
  PDA: "DeFi",

  LINK: "Oracle",
  BAND: "Oracle",
  PYTH: "Oracle",
  PRQ: "Oracle",

  FET: "AI",
  RNDR: "AI",
  TAO: "AI",
  ATH: "AI",
  CORGIAI: "AI",
  ALI: "AI",
  ASM: "AI",

  GRT: "Web3",
  BAT: "Web3",
  ENS: "Web3",
  STORJ: "Storage",
  DAG: "Web3",
  IQ: "Web3",
  XYO: "Web3",
  DNT: "Web3",
  NCT: "Web3",
  RADAR: "Web3",
  KRL: "Web3",

  SAND: "Metaverse",
  MANA: "Metaverse",
  AXS: "Gaming",
  GALA: "Gaming",
  ENJ: "Gaming",
  CHZ: "Gaming",
  GMT: "Gaming",
  BEAMX: "Gaming",
  MBL: "Gaming",

  SHIB: "Memecoin",
  PEPE: "Memecoin",
  DOGE: "Memecoin",
  FLOKI: "Memecoin",
  BONK: "Memecoin",
  ELON: "Memecoin",
  WOJAK: "Memecoin",
  MONKY: "Memecoin",
  TOSHI: "Memecoin",
  SUNDOG: "Memecoin",
  PENGU: "Memecoin",
  BARA: "Memecoin",
  CAW: "Memecoin",
  DOGS: "Memecoin",
  AWE: "Memecoin",

  USDT: "Stablecoin",
  USDC: "Stablecoin",
  DAI: "Stablecoin",
  BUSD: "Stablecoin",
  TUSD: "Stablecoin",
  RLUSD: "Stablecoin",

  WBTC: "DeFi",
  STETH: "Staking",
  WETH: "DeFi",
  RETH: "Staking",
  CBETH: "Staking",
  MSOL: "Staking",
  JTO: "Staking",
  HBARX: "Staking",

  CRO: "Finance",
  LEO: "Finance",
  OKB: "Finance",
  QNT: "Finance",
  XDC: "Finance",
  SOLO: "Finance",
  ONDO: "RWA",
  PRO: "RWA",

  APE: "NFT",
  BLUR: "NFT",

  FLR: "Smart Contracts",
  INJ: "DeFi",
  JASMY: "IoT",
  IOTX: "IoT",

  HEX: "DeFi",
  RSR: "Finance",
  AMP: "Finance",
  ACH: "Finance",
  XPR: "Finance",
  COTI: "Finance",

  LTC: "Layer 1",
  BCH: "Layer 1",
  ETC: "Layer 1",
  XMR: "Privacy",
  ZEC: "Privacy",
  DASH: "Privacy",
  DGB: "Layer 1",
  RVN: "Layer 1",
  XVG: "Privacy",

  TRX: "Layer 1",
  BTT: "Web3",
  VET: "Supply Chain",
  VTHO: "Supply Chain",

  LUNC: "Layer 1",
  S: "Layer 1",
  IOST: "Layer 1",
  MOBILE: "IoT",
  STMX: "Finance",
  ARPA: "Privacy",
  ZRX: "DeFi",
  OMG: "Layer 2",
  NXRA: "DeFi",
  MXC: "IoT",
  QSP: "DeFi",
  LSS: "DeFi",
  VRA: "Web3",
  XCN: "DeFi",
  EPX: "DeFi",
  COS: "Web3",
  ZBCN: "Finance",
  WSOL: "Layer 1",
  PEAQ: "IoT",
  AITECH: "AI",
  CNQ: "Finance",
  "$ADS": "Web3",
  CLXY: "DeFi",
};

export const CATEGORY_COLORS: Record<string, string> = {
  "Layer 1": "hsl(210, 70%, 50%)",
  "Layer 2": "hsl(240, 60%, 55%)",
  "DeFi": "hsl(150, 60%, 45%)",
  "Smart Contracts": "hsl(280, 60%, 55%)",
  "Finance": "hsl(30, 70%, 50%)",
  "Memecoin": "hsl(350, 70%, 55%)",
  "Gaming": "hsl(170, 60%, 45%)",
  "Metaverse": "hsl(300, 50%, 50%)",
  "AI": "hsl(200, 80%, 50%)",
  "Oracle": "hsl(45, 80%, 50%)",
  "Web3": "hsl(190, 60%, 45%)",
  "Stablecoin": "hsl(120, 40%, 50%)",
  "Staking": "hsl(260, 50%, 55%)",
  "NFT": "hsl(320, 60%, 55%)",
  "RWA": "hsl(15, 70%, 50%)",
  "IoT": "hsl(180, 60%, 45%)",
  "Storage": "hsl(60, 50%, 45%)",
  "Privacy": "hsl(0, 50%, 45%)",
  "Supply Chain": "hsl(100, 50%, 45%)",
  "Internet": "hsl(220, 70%, 55%)",
  "Other": "hsl(0, 0%, 50%)",
};

export function getAssetCategory(symbol: string): string {
  return ASSET_CATEGORIES[symbol.toUpperCase()] || "Other";
}
