export const KNOWN_XRPL_ADDRESSES: Record<string, string> = {
  "rEb8TK3gBgk5auZkwc6sHnwrGVJH8DuaLh": "Binance",
  "rNxp4h8apvRis6mJf9Sh8C6iRxfrDWN7AV": "Binance",
  "rPz2qA8PNMGSVyEETii6aGrbMgKBJoUKhS": "Binance",
  "rs8ZPbYqgecRjdMRuRFSGCz9Y5fGvJKkTH": "Binance",
  "rBg2FuYrBivMDqSMvbam3YqpRfGBdGbhDo": "Binance",
  "rEy8TFcrAPvhpKrwyrscNYyqBGUkE9hKaJ": "Binance Cold Wallet",
  "rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq": "GateHub",
  "rchGBxcD1A1C2tdxF6papQYZ8kjRKMYcL": "GateHub",
  "rDsbeomae4FXwgQTJp9Rs64Qg9vDiTCdBv": "GateHub",
  "rnwiEKY2FAfib6LpA9KM5JBmgCNuZ3wB9f": "GateHub",
  "rHcFoo6a9qT5NHiVn1THQRhsEGcxtYCV15": "Bitstamp",
  "rrpNnNLKrartuEqfJGpqyDwPj1AFPg9vn1": "Bitstamp",
  "rGFuMiw48HdbnrUbkRYuitReWvFYzbGg4V": "Bitstamp",
  "rDAN8tzydyNfnNf2bfUQY6iR96UbpvNsze": "Bitstamp",
  "rKiCet8SdvWxPXnAgYarFUXMh1zCPz432Y": "Bitstamp Cold Wallet",
  "rLHzPsX6oXkzU2qL12kHCH8G8cnZv1rBJh": "Bitstamp Cold Wallet",
  "r9cZA1mLK5R5Am25ArfXFmqgNwjZgnfk59": "Ripple",
  "rKveEyR1SrkWbJX214xcfH43ZkY2s1cFQJ": "Ripple",
  "rN7n3473SaZBCG4dFL83w7p1W9cgPW7L3D": "Ripple OTC",
  "rHb9CJAWyB4rj91VRWn96DkukG4bwdtyTh": "Ripple Genesis",
  "rpXCfDds782Bd6eK6GprMhp1kDefqJEGiS": "Ripple",
  "rPEPPER7kfTD9w2To4CQk6UCfuHM9c6GDY": "Ripple",
  "rfkE1aSy9G8Upk4JssnwBxhEv5p4mn2KTy": "Ripple",
  "rB3gZey7VWHYRqJHLoHDEJXJ2pEPNieKiS": "Ripple",
  "rMQ98K56yXJbDGv49ZSmW51sLn94Ge1KhN": "Ripple Escrow",
  "rMsYhifdvPdHfMxWC62acPf7z6FE9KWBGA": "Ripple Escrow",
  "r3kmLJN5D28dHuH8vZNUZpMC43pEHpaocV": "Ripple",
  "rLqUC2eCPohYvJCEBJ77eCCqVL2uEiczjA": "Uphold",
  "rPECVKwaMuBAfGpD2wxrQwEUb6Ctk5Z7hP": "Uphold",
  "rU7k1r9rqNotcut2rmCpJYgz8HXCT1Ehpj": "Uphold",
  "rBKz5MC2iXdoS3XgnNSYmF69K1Yo4NS3Ws": "Crypto.com",
  "rHPaKDjV2kJcTMJRMPbT4mt73aeqZVfT5j": "Crypto.com",
  "rw2ciyaNshpHe7bCHo4bRWq6pqqynnWKQg": "Kraken",
  "rLHnCPtQ5p4d872LAheYhniQVb6T8UFvBo": "Kraken",
  "rN4TD47roSy99Jvj3WKf5ts4xxA2RwRcoD": "Kraken",
  "re3pNqTqeogUFkqxB9xpBLiMEUFHPgiSz8": "Kraken",
  "rLNaPoKeeBjZe2qs6x52yVPKpJzKkYk5a9": "Kraken",
  "rDbWJ9C7uExThZYAwV8m6LsZ5YSX3sa6US": "Bittrex",
  "rGDreBvnHrX1get7na3CE4UrAbkWta8yS1": "Bittrex",
  "rPVMhWBsfF9iMXYj3aAzJVkPDTFNSyWdKy": "BTCMarkets",
  "r3fqaHtt28dY5gfi3bM2ANxEDz4CsJkMf2": "Coinone",
  "rG6FZ31hDHN1K5Dkbma3PSB5uVCuVVRzfn": "Bitfinex",
  "rLW9gnQo3BQhU6igk5keqYnH3TVrCxGRzm": "Bitfinex",
  "rB3mFZrMVUrk8FRr3k7a7DLXwTMbrzbeGF": "Bitfinex",
  "rDMFJrKg2nTqBBA3EEMnjyfGHe7MEyR1Bn": "Huobi",
  "r9do2Ar8b7DziNqnMHkzRhEYnE3Q87W3AJ": "Huobi",
  "rEDakigd4Cp78FioFETgMnPquP549Hx58E": "Huobi",
  "rEy1qcFo7HACLqFngwMyUHbqkx3pEcYSvE": "KuCoin",
  "rwCUBYvjoJkJBXajR55avo87JgNDMgf9WF": "KuCoin",
  "rU2mEJSLqBRkYLVTv55rFTgQajkLTnT6mA": "Bitso",
  "rfESTMcbvbvCBqU1FTvGWiJP8cmUSu4GKg": "Bitso",
  "rNQEMJA4PsoSrZRn9J6RajAYhcDzzhf8ok": "Coins.ph",
  "rJb5KsHsDHF1YS5B5DU6QCkH5NsPaGQTN6": "SBI VC Trade",
  "rMxCKbEDwqr76QuheSUMdEGf4B9xJ8m5De": "RLUSD Issuer (Ripple)",
  "rHKx9ngSgQUQGMSrP313hFKDukvJXdVfBX": "Soil Protocol (Credit+)",
  "rnvp6FiucXE7kjR8LKRocosWmg8pGhFZa8": "Soil Protocol (Liquid)",
  "rPdvC6ccq8hCdPKSPJkPmyZ4Mi1oG2FFkT": "XRP Foundation",
  "rrrrrrrrrrrrrrrrrrrrrhoLvTp": "XRPL Account Zero (Black Hole)",
  "rrrrrrrrrrrrrrrrrrrrBZbvji": "XRPL NaN Account (Black Hole)",
  "rrrrrrrrrrrrrrrrrNAMEtxvNvQ": "XRPL Name Reservation (Black Hole)",
  "rLFd1FzHPScRHmSV7bqSYyGYB9cXRUMNnn": "Coinbase",
  "rw2ZxN37YmDzegQ4k2QLQM1LFcyUmTqXW8": "Coinbase",
  "rN7JqRThmPBerkTKoZ1YkLpXvKnGcPuD1A": "Coinbase",
  "r3ADD8kXSUKHd6zTCKfnKT3ZV9EhHjBB4e": "XRP Labs / XUMM",
  "rNFugeoj3ZN8Wv6xhuCGgnMrP3MNZLPEQR": "Towo Labs",
  "rPt8kmjEyjCriqvzAsBEnEYhJFuKtCfEpb": "OKX",
  "rwfGzgpjbXYe8VPCoxk1M7eMZUjU2rbcai": "OKX",
  "rsi3GL27pstEYUJ4fD6eaMoivw7rKfnCqS": "OKX",
  "ra5nK24KXen9AHvsdFTKHSANinZseWnPcX": "Bybit",
  "rJHygWcTLVpSXzfoc10d2EU8w1hBpiwuy6": "Bybit",
  "rhWt2JFPbQth1F2xbEzMVqiGJ7kJhjHMpS": "First Ledger",
  "rMQ4oGC4sHbihH8FinFyWFTGYSAYvWmSKe": "eToro",
  "r4qr4iSaBBaJLGHRBC6NxAaYdHfqzmRi3P": "eToro",
  "rsP3mgGb2tcYUrxiLFiHJiQXhsziegtwBc": "Bithumb",
  "rNQao3Z1irwRjKWSs8heL4a8WKLPKsNRNY": "Bithumb",
  "rUobSiUpYH2S1tZh1c8mFmg94tsgMHMPTn": "MEXC",
  "rJzaMkEr6sADqJrKiVCWfkHbRPyx7iam6L": "BitGo",
  "rwWr7KUZ3ZFwzgaDGjKBysADByzxvohQ3C": "CEX.io",
};
